# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to 5.2.17
  #- 5.2
  # aliased to 5.3.29
  #- 5.3
  # aliased to a recent 5.4.x version
  #- 5.4
  # aliased to a recent 5.5.x version
  #- 5.5
  # aliased to a recent 5.6.x version
  #- 5.6
  # aliased to a recent 7.x version
  #- 7.0
  # aliased to a recent 7.1 version
  - 7.1
  # aliased to a recent 7.0 version
  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=pgsql
  global:
    - "FTP_USER=travistest"
    - "FTP_PASSWORD=testtravis"

# optionally set up exclusions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.1
    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose up --build -d

script: 
    - echo 'ok'

# configure notifications (email, IRC, campfire etc)
notifications:
  email: andrey@uma.ru

after_success:
  "curl --upload-file -u $FTP_USER:$FTP_PASSWORD ftp://www.uma.ru/www/"
  